# -*- coding: utf-8 -*-
"""
Created on Mon Oct 24 17:16:12 2022

@author: User 11
"""

print(f"Talaba {talaba_1['ism'].title()} {talaba_1['kurs']}-kursda ")
print(f"Talaba {talaba_1['ism'].title()} {talaba_1['kurs']}-kursda ")
print(f"Talaba {talaba_1['ism'].title()} {talaba_1['kurs']}-kursda ")
print(f"Talaba {talaba_1['ism'].title()} {talaba_1['kurs']}-kursda ")
print(f"Talaba {talaba_1['ism'].title()} {talaba_1['kurs']}-kursda ")
print(f"Talaba {talaba_1['ism'].title()} {talaba_1['kurs']}-kursda ")
print(f"Talaba {talaba_1['ism'].title()} {talaba_1['kurs']}-kursda ")
print(f"Talaba {talaba_1['ism'].title()} {talaba_1['kurs']}-kursda ")
print(f"Talaba {talaba_1['ism'].title()} {talaba_1['kurs']}-kursda ")
print(f"Talaba {talaba_1['ism'].title()} {talaba_1['kurs']}-kursda ")
print(f"Talaba {talaba_1['ism'].title()} {talaba_1['kurs']}-kursda ")
print(f"Talaba {talaba_1['ism'].title()} {talaba_1['kurs']}-kursda ")
print(f"Talaba {talaba_1['ism'].title()} {talaba_1['kurs']}-kursda ")
print(f"Talaba {talaba_1['ism'].title()} {talaba_1['kurs']}-kursda ")
print(f"Talaba {talaba_1['ism'].title()} {talaba_1['kurs']}-kursda ")
print(f"Talaba {talaba_1['ism'].title()} {talaba_1['kurs']}-kursda ")
print(f"Talaba {talaba_1['ism'].title()} {talaba_1['kurs']}-kursda ")
print(f"Talaba {talaba_1['ism'].title()} {talaba_1['kurs']}-kursda ")
print(f"Talaba {talaba_1['ism'].title()} {talaba_1['kurs']}-kursda ")
print(f"Talaba {talaba_1['ism'].title()} {talaba_1['kurs']}-kursda ")
print(f"Talaba {talaba_1['ism'].title()} {talaba_1['kurs']}-kursda ")
print(f"Talaba {talaba_1['ism'].title()} {talaba_1['kurs']}-kursda ")
print(f"Talaba {talaba_1['ism'].title()} {talaba_1['kurs']}-kursda ")
print(f"Talaba {talaba_1['ism'].title()} {talaba_1['kurs']}-kursda ")
print(f"Talaba {talaba_1['ism'].title()} {talaba_1['kurs']}-kursda ")
print(f"Talaba {talaba_1['ism'].title()} {talaba_1['kurs']}-kursda ")
print(f"Talaba {talaba_1['ism'].title()} {talaba_1['kurs']}-kursda ")
print(f"Talaba {talaba_1['ism'].title()} {talaba_1['kurs']}-kursda ")
print(f"Talaba {talaba_1['ism'].title()} {talaba_1['kurs']}-kursda ")
print(f"Talaba {talaba_1['ism'].title()} {talaba_1['kurs']}-kursda ")
print(f"Talaba {talaba_1['ism'].title()} {talaba_1['kurs']}-kursda ")
print(f"Talaba {talaba_1['ism'].title()} {talaba_1['kurs']}-kursda ")
print(f"Talaba {talaba_1['ism'].title()} {talaba_1['kurs']}-kursda ")
print(f"Talaba {talaba_1['ism'].title()} {talaba_1['kurs']}-kursda ")
print(f"Talaba {talaba_1['ism'].title()} {talaba_1['kurs']}-kursda ")
print(f"Talaba {talaba_1['ism'].title()} {talaba_1['kurs']}-kursda ")
print(f"Talaba {talaba_1['ism'].title()} {talaba_1['kurs']}-kursda ")
print(f"Talaba {talaba_1['ism'].title()} {talaba_1['kurs']}-kursda ")
print(f"Talaba {talaba_1['ism'].title()} {talaba_1['kurs']}-kursda ")
print(f"Talaba {talaba_1['ism'].title()} {talaba_1['kurs']}-kursda ")
print(f"Talaba {talaba_1['ism'].title()} {talaba_1['kurs']}-kursda ")
print(f"Talaba {talaba_1['ism'].title()} {talaba_1['kurs']}-kursda ")
print(f"Talaba {talaba_1['ism'].title()} {talaba_1['kurs']}-kursda ")
print(f"Talaba {talaba_1['ism'].title()} {talaba_1['kurs']}-kursda ")
print(f"Talaba {talaba_1['ism'].title()} {talaba_1['kurs']}-kursda ")
print(f"Talaba {talaba_1['ism'].title()} {talaba_1['kurs']}-kursda ")
